name: Auto Assign Reviewer from Team

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Asignar revisor aleatorio desde el equipo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT_READ_ORG }}
          script: |
            const pr = context.payload.pull_request;
            const creator = pr.user.login;

            // Obtener miembros del equipo "reviewers"
            const { data: members } = await github.rest.teams.listMembersInOrg({
              org: 'JLL-Company',
              team_slug: 'reviewers',
            });

            const teamMembers = members.map(member => member.login);
            const reviewers = teamMembers.filter(user => user !== creator);

            if (reviewers.length === 0) {
              console.log('No hay revisores disponibles (todos menos el autor)');
              return;
            }

            const reviewer = reviewers[Math.floor(Math.random() * reviewers.length)];

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers: [reviewer],
            });

            console.log(`Revisor asignado: ${reviewer}`);
